openapi: 3.0.0
info:
  contact: {}
  title: Time tracking
  version: 1.0.0
servers:
- url: /
paths:
  /session:
    get:
      parameters:
      - explode: true
        in: query
        name: timeframe
        required: false
        schema:
          type: string
        style: form
      responses:
        default:
          description: Default response
    post:
      parameters: []
      responses:
        default:
          description: Default response
    put:
      parameters:
      - explode: true
        in: query
        name: session_group_id
        required: false
        schema:
          type: string
        style: form
      responses:
        default:
          description: Default response
  /session/{id}:
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: stop
        required: false
        schema:
          type: string
        style: form
      responses:
        default:
          description: Default response
components:
  callbacks: {}
  links: {}
  schemas: {}
